"""Interactive UAV planning and control entry point."""

from __future__ import annotations

import os
from typing import Literal

# GCOPTER solves many tiny systems; extra BLAS workers reduce throughput.
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")

from uav_ac import utils
from uav_ac.control import TrajectoryController
from uav_ac.runtime import (
    ControllerName,
    PlannerName,
    build_controller as _build_controller,
    mission_for_scene as _mission_for_scene,
    plan_scene_trajectory as _plan_scene_trajectory,
    plan_trajectory as _plan_trajectory,
    run_interactive_flight as _run_interactive_flight,
    sample_open_field_mission as _sample_open_field_mission,
    scene_path as _scene_path,
    trajectory_after_takeoff as _trajectory_after_takeoff,
    wind_control_callbacks as _wind_control_callbacks,
)
from uav_ac.planning.pipeline import generate_minimum_snap_mission as _generate_mission_trajectory
from uav_ac.simulation.mujoco_sim import MujocoSimulation


SceneName = Literal["lab_course", "open_field", "gcs_building"]
VISUALIZE: bool = False
PLANNER: PlannerName = "gcopter"                #PlannerName = Literal["mini_snap", "gcopter", "gcs"]
CONTROLLER: ControllerName = "rl"         #ControllerName = Literal["cascaded", "mpc", "rl"] rl can only follow traj that generated by gcopter
SCENE: SceneName = "lab_course"
WIND_ENABLED: bool = False
RL_RUN_DIR: str = "runs/ppo_trajectory/multitraj01"
OPEN_FIELD_SEED: int = 51
OPEN_FIELD_MAX_SPEED: float = 4.0


def main() -> None:
    cfg, cfg_flight = utils.get_config()
    steps_per_reference = cfg.getint("frequency")
    velocity = cfg_flight.getfloat("velocity")
    selected_scene = _scene_path(PLANNER, SCENE)
    simulation = MujocoSimulation(selected_scene)
    trajectory_dt = simulation.quad.dt * steps_per_reference
    controller = _build_controller(
        CONTROLLER, simulation.quad, trajectory_dt, run_dir=RL_RUN_DIR)
    waypoints, scene_velocity = _mission_for_scene(
        simulation, selected_scene, OPEN_FIELD_SEED, OPEN_FIELD_MAX_SPEED)
    trajectory = _plan_scene_trajectory(
        PLANNER,
        simulation,
        selected_scene,
        waypoints,
        trajectory_dt,
        velocity if scene_velocity is None else scene_velocity,
        visualize=VISUALIZE,
    )
    simulation.set_trajectory_visualization(trajectory[:, :3])
    _run_interactive_flight(
        simulation,
        controller,
        trajectory,
        steps_per_reference,
        cfg_flight.getfloat("min_dist_target"),
        selected_scene,
        CONTROLLER,
        WIND_ENABLED,
    )


if __name__ == "__main__":
    main()
