"""Configuration for Fast Iterative Region Inflation."""

from dataclasses import dataclass


@dataclass(frozen=True)
class FIRIConfig:
    """Numerical settings shared by all regions generated by a planner."""

    max_iterations: int = 2
    convergence_tolerance: float = 0.02
    max_planes: int = 96
    mvie_max_iterations: int = 128
    mvie_smoothing: float = 1.0e-2
    mvie_penalty: float = 1.0e3

    def __post_init__(self) -> None:
        if (self.max_iterations <= 0 or self.max_planes < 6
                or self.mvie_max_iterations <= 0):
            raise ValueError(
                "iteration counts must be positive and max_planes at least six")
        if (self.convergence_tolerance < 0.0 or self.mvie_smoothing <= 0.0
                or self.mvie_penalty <= 0.0):
            raise ValueError(
                "convergence tolerance must be non-negative and MVIE settings positive")
